name: qr_ticket_scanner
description: "A Flutter QR ticket scanning application."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1  # For QR scanning functionality
  http: ^1.1.0  # For API calls
 # For date/time formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6  # For code generation
  mockito: ^5.4.2  # For testing (optional)

flutter:
  uses-material-design: true
 # Add your asset paths here